package com.wuyufei.domain;
// Generated 2015-7-3 19:47:40 by Hibernate Tools 3.4.0.CR1

/**
 * Bussiness generated by hbm2java
 */
public class Bussiness implements java.io.Serializable {

	private String userName;
	private int time;
	private String area;
	private float fare;

	public Bussiness() {
	}

	public Bussiness(String userName, int time, String area, float fare) {
		this.userName = userName;
		this.time = time;
		this.area = area;
		this.fare = fare;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public float getFare() {
		return this.fare;
	}

	public void setFare(float fare) {
		this.fare = fare;
	}

}
