package com.wuyufei.domain;
// Generated 2015-7-4 15:27:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderList generated by hbm2java
 */
public class OrderList implements java.io.Serializable {

	private Integer orderId;
	private Userinfo userinfo;
	private String productName;
	private int price;
	private int qty;
	private String telephone;
	private String address;
	private Date inserttime;

	public OrderList() {
	}

	public OrderList(Userinfo userinfo, String productName, int price, int qty,
			String telephone, String address, Date inserttime) {
		this.userinfo = userinfo;
		this.productName = productName;
		this.price = price;
		this.qty = qty;
		this.telephone = telephone;
		this.address = address;
		this.inserttime = inserttime;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getInserttime() {
		return this.inserttime;
	}

	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

}
