package com.wuyufei.domain;
// Generated 2015-7-6 15:16:27 by Hibernate Tools 3.4.0.CR1

/**
 * Sales generated by hbm2java
 */
public class Sales implements java.io.Serializable {

	private Integer salesId;
	private String username;
	private String dishname;
	private float dishprice;

	public Sales() {
	}

	public Sales(String username, String dishname, float dishprice) {
		this.username = username;
		this.dishname = dishname;
		this.dishprice = dishprice;
	}

	public Integer getSalesId() {
		return this.salesId;
	}

	public void setSalesId(Integer salesId) {
		this.salesId = salesId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDishname() {
		return this.dishname;
	}

	public void setDishname(String dishname) {
		this.dishname = dishname;
	}

	public float getDishprice() {
		return this.dishprice;
	}

	public void setDishprice(float dishprice) {
		this.dishprice = dishprice;
	}

}
