package com.wuyufei.domain;
// Generated 2015-7-4 15:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Salesinfo generated by hbm2java
 */
public class Salesinfo implements java.io.Serializable {

	private String username;
	private Userinfo userinfo;
	private String dishName;
	private float dishPrice;

	public Salesinfo() {
	}

	public Salesinfo(Userinfo userinfo, String dishName, float dishPrice) {
		this.userinfo = userinfo;
		this.dishName = dishName;
		this.dishPrice = dishPrice;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public String getDishName() {
		return this.dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	public float getDishPrice() {
		return this.dishPrice;
	}

	public void setDishPrice(float dishPrice) {
		this.dishPrice = dishPrice;
	}

}
