package com.wuyufei.domain;
// Generated 2015-7-4 15:27:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private String username;
	private String password;
	private String email;
	private String telephone;
	private Salesinfo salesinfo;
	private Bussiness bussiness;
	private Set orderLists = new HashSet(0);

	public Userinfo() {
	}

	public Userinfo(String username, String password, String email,
			String telephone) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.telephone = telephone;
	}

	public Userinfo(String username, String password, String email,
			String telephone, Salesinfo salesinfo, Bussiness bussiness,
			Set orderLists) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.telephone = telephone;
		this.salesinfo = salesinfo;
		this.bussiness = bussiness;
		this.orderLists = orderLists;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Salesinfo getSalesinfo() {
		return this.salesinfo;
	}

	public void setSalesinfo(Salesinfo salesinfo) {
		this.salesinfo = salesinfo;
	}

	public Bussiness getBussiness() {
		return this.bussiness;
	}

	public void setBussiness(Bussiness bussiness) {
		this.bussiness = bussiness;
	}

	public Set getOrderLists() {
		return this.orderLists;
	}

	public void setOrderLists(Set orderLists) {
		this.orderLists = orderLists;
	}

}
